name: Main
on:
  push:
    branches: [main, hotfix]
    tags-ignore: ['**']

jobs:
  build:
    name: Build
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/service.yml
    with:
      deploy: true
